
# -*- coding: utf-8 -*-
"""ba class 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAsRyQ1WVXQ-X48Sa3qOmvOPWhQJH9SY
"""

import pandas as pd

df=pd.read_csv("/content/delivery_delay.csv")

df

X=df.drop(['Delivery_Delay'],axis=1)
y=df['Delivery_Delay']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

X.columns

model.predict([[12,2,1,2,4,3,3,3,12,10,90]])

model.predict_proba([[12,2,1,2,4,3,3,3,12,10,90]])

model.score(X_test, y_test)

"""Can you make confusion matrix from this data"""

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No Delay', 'Predicted Delay'],
            yticklabels=['Actual No Delay', 'Actual Delay'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)
print(f'Recall on test data: {recall:.2f}')

from sklearn.model_selection import cross_val_score

cv_recall_scores = cross_val_score(model, X, y, cv=5, scoring='recall')

print(f'Cross-validation Recall Scores: {cv_recall_scores}')
print(f'Mean Cross-validation Recall: {cv_recall_scores.mean():.2f}')

import joblib

joblib.dump(model, "model.sav")
Create an app file for this

Yes. I created a Streamlit app for your Logistic Regression delivery-delay model.

Files


Folder structure
delivery-delay-app/
│
├── app.py
├── model.sav
├── requirements.txt
└── delivery_delay.csv   # optional, not needed for prediction
Important: Put your existing model.sav in the same folder as app.py.

Run the app
Open Command Prompt/Terminal in that folder:

pip install -r requirements.txt
streamlit run app.py
The app will open in your browser and provide 11 input fields, followed by:

✅ No Delivery Delay / ⚠️ Delivery Delay

Probability of No Delay

Probability of Delay

I used the 11 input variables in the same order as your model's prediction example:

[12, 2, 1, 2, 4, 3, 3, 3, 12, 10, 90]
If you give me the actual column names from delivery_delay.csv, I can also make the app much better by replacing Feature 1, Feature 2, etc. with meaningful field names and appropriate dropdowns/sliders. 




Library
/
app.py


12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
import streamlit as st
# Load trained model
@st.cache_resource
def load_model():
    return joblib.load("model.sav")

model = load_model()

st.title("🚚 Delivery Delay Predictor")
st.write("Enter the delivery/order details below to predict whether the delivery will be delayed.")

st.divider()

# The model was trained with these 11 features, in this order:
# [12,2,1,2,4,3,3,3,12,10,90]
feature_names = [
    "Feature 1", "Feature 2", "Feature 3", "Feature 4", "Feature 5",
    "Feature 6", "Feature 7", "Feature 8", "Feature 9", "Feature 10",
    "Feature 11"
]

# Create input fields
cols = st.columns(2)
inputs = []

for i, name in enumerate(feature_names):
    with cols[i % 2]:
        value = st.number_input(
            name,
            value=0.0,
            step=1.0,
            help=f"Enter value for {name}"
        )
        inputs.append(value)

st.divider()

if st.button("Predict Delivery Delay", type="primary", use_container_width=True):
    input_data = np.array(inputs).reshape(1, -1)

    prediction = model.predict(input_data)[0]
    probabilities = model.predict_proba(input_data)[0]

    # Assumes 0 = No Delay and 1 = Delay
    if prediction == 1:
        st.error("⚠️ Prediction: DELIVERY DELAY")
    else:
        st.success("✅ Prediction: NO DELIVERY DELAY")

    st.subheader("Prediction Probability")

    classes = model.classes_
    prob_df = pd.DataFrame({
        "Outcome": [
            "No Delay" if c == 0 else "Delay"
            for c in classes
        ],
        "Probability": probabilities
    })

    for _, row in prob_df.iterrows():
        st.write(f"**{row['Outcome']}**: {row['Probability']:.2%}")
        st.progress(float(row["Probability"]))

st.caption("Model: Logistic Regression | Trained using delivery_delay.csv")

