# -*- coding: utf-8 -*-
"""ba class 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAsRyQ1WVXQ-X48Sa3qOmvOPWhQJH9SY
"""

import pandas as pd

df=pd.read_csv("/content/delivery_delay.csv")

df

X=df.drop(['Delivery_Delay'],axis=1)
y=df['Delivery_Delay']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

X.columns

model.predict([[12,2,1,2,4,3,3,3,12,10,90]])

model.predict_proba([[12,2,1,2,4,3,3,3,12,10,90]])

model.score(X_test, y_test)

"""Can you make confusion matrix from this data"""

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No Delay', 'Predicted Delay'],
            yticklabels=['Actual No Delay', 'Actual Delay'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)
print(f'Recall on test data: {recall:.2f}')

from sklearn.model_selection import cross_val_score

cv_recall_scores = cross_val_score(model, X, y, cv=5, scoring='recall')

print(f'Cross-validation Recall Scores: {cv_recall_scores}')
print(f'Mean Cross-validation Recall: {cv_recall_scores.mean():.2f}')

import joblib

joblib.dump(model, "model.sav")

